name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        include:
          - os: ubuntu-22.04
            platform: manylinux2014_x86_64
          - os: ubuntu-22.04
            platform: manylinux2014_aarch64
            arch: arm64
          - os: macos-12
            platform: macosx_11_0_arm64
          - os: macos-12
            platform: macosx_10_15_x86_64
          - os: windows-2022
            platform: win_amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: |
          python setup.py bdist_wheel --plat-name ${{ matrix.platform }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.platform }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheel-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true