name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64, macos-13, macos-latest, windows-2022]
        include:
          - os: ubuntu-latest
            platform: manylinux2014_x86_64
            arch: x64
          - os: ubuntu-latest-arm64
            platform: manylinux2014_aarch64
            arch: arm64
          - os: macos-13
            platform: macosx_10_15_x86_64
          - os: macos-latest
            platform: macosx_14_0_arm64
            arch: arm64
          - os: windows-2022
            platform: win_amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        shell: bash
        run: |
          if [[ "${{ matrix.platform }}" == manylinux* ]]; then
            python setup.py bdist_wheel --plat-name ${{ matrix.platform }} --python-tag py3
          else
            python setup.py bdist_wheel --plat-name ${{ matrix.platform }} --python-tag py3
          fi

      - name: Build sdist
        run: |
          python setup.py sdist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.platform }}-${{ matrix.arch || 'x64' }}
          path: |
            dist/*.whl
            dist/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheel-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: false
          package-dir: dist/