name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest, windows-2022]
        include:
          - os: ubuntu-latest
            platform: manylinux2014_x86_64
            arch: x64
          - os: ubuntu-24.04-arm
            platform: manylinux2014_aarch64
            arch: arm64
          - os: macos-13
            platform: macosx_10_15_x86_64
          - os: macos-latest
            platform: macosx_14_0_arm64
            arch: arm64
          - os: windows-2022
            platform: win_amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        shell: bash
        env:
          TARGET_PLATFORM: ${{ matrix.platform }}_${{ matrix.arch || 'x64' }}  # 例如manylinux2014_x86_64_x64
        run: |
          # 转换平台标识到简写格式
          case "${{ matrix.platform }}" in
            manylinux2014_x86_64*)
              export TARGET_PLATFORM=linux_x86_64
              ;;
            manylinux2014_aarch64*)
              export TARGET_PLATFORM=linux_aarch64
              ;;
            macosx_10_15_x86_64*)
              export TARGET_PLATFORM=macos_x86_64
              ;;
            macosx_14_0_arm64*)
              export TARGET_PLATFORM=macos_arm64
              ;;
            win_amd64*)
              export TARGET_PLATFORM=win_amd64
              ;;
          esac
          
          python setup.py bdist_wheel --plat-name ${{ matrix.platform }} --python-tag py3

      - name: Build sdist
        run: |
          python setup.py sdist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.platform }}-${{ matrix.arch || 'x64' }}
          path: |
            dist/*.whl
            dist/*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: merged_dist
          pattern: dist-*
          merge-multiple: true

      - name: Prepare dist directory
        run: |
          mkdir -p dist
          find merged_dist -name '*.whl' -exec cp {} dist/ \;
          find merged_dist -name '*.tar.gz' -exec cp {} dist/ \;

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: false
          package-dir: dist/